import type { Metadata } from "next";
import { Ubuntu, Fira_Code } from "next/font/google";
import "./globals.css";
// import Navbar from "@/lib/components/Navbar";

// Metadata
export const metadata: Metadata = {
  title: "MohammadDev",
  description: "Generated by create next app",
};

// Fonts
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ubuntu",
});

const fira = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-fira",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${ubuntu.variable} ${fira.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
